export const cards = [
  { id: "baa-absolution", name: "Absolution", image: "baa-absolution.webp" },
  {
    id: "baa-alejandro-lopez",
    name: "Alejandro Lopez",
    image: "baa-alejandro-lopez.webp",
  },
  {
    id: "baa-all-the-angles",
    name: "All the Angles",
    image: "baa-all-the-angles.webp",
  },
  { id: "baa-april-smith", name: "April Smith", image: "baa-april-smith.webp" },
  {
    id: "baa-athanor-corporis",
    name: "Athanor Corporis",
    image: "baa-athanor-corporis.webp",
  },
  { id: "baa-aurora-nix", name: "Aurora Nix", image: "baa-aurora-nix.webp" },
  {
    id: "baa-baals-caress",
    name: "Baal's Caress",
    image: "baa-baals-caress.webp",
  },
  {
    id: "baa-back-to-formula",
    name: "Back to Formula",
    image: "baa-back-to-formula.webp",
  },
  { id: "baa-backup", name: "Backup", image: "baa-backup.webp" },
  {
    id: "baa-blood-makes-noise",
    name: "Blood Makes Noise",
    image: "baa-blood-makes-noise.webp",
  },
  {
    id: "baa-blood-of-potency",
    name: "Blood of Potency",
    image: "baa-blood-of-potency.webp",
  },
  { id: "baa-break-down", name: "Break Down", image: "baa-break-down.webp" },
  { id: "baa-calcinatio", name: "Calcinatio", image: "baa-calcinatio.webp" },
  {
    id: "baa-caleb-walker",
    name: "Caleb Walker",
    image: "baa-caleb-walker.webp",
  },
  { id: "baa-candi-liu", name: "Candi Liu", image: "baa-candi-liu.webp" },
  {
    id: "baa-claudia-sterling",
    name: "Claudia Sterling",
    image: "baa-claudia-sterling.webp",
  },
  { id: "baa-crossbow", name: "Crossbow", image: "baa-crossbow.webp" },
  {
    id: "baa-dangerous-mixture",
    name: "Dangerous Mixture",
    image: "baa-dangerous-mixture.webp",
  },
  {
    id: "baa-darius-wolfe",
    name: "Darius Wolfe",
    image: "baa-darius-wolfe.webp",
  },
  {
    id: "baa-defense-of-the-sacred-haven",
    name: "Defense of the Sacred Haven",
    image: "baa-defense-of-the-sacred-haven.webp",
  },
  { id: "baa-enervate", name: "Enervate", image: "baa-enervate.webp" },
  { id: "baa-envelop", name: "Envelop", image: "baa-envelop.webp" },
  {
    id: "baa-extinguish-vitae",
    name: "Extinguish Vitae",
    image: "baa-extinguish-vitae.webp",
  },
  { id: "baa-faith-gray", name: "Faith Gray", image: "baa-faith-gray.webp" },
  { id: "baa-far-reach", name: "Far Reach", image: "baa-far-reach.webp" },
  {
    id: "baa-first-ones-free",
    name: "First One's Free",
    image: "baa-first-ones-free.webp",
  },
  { id: "baa-fixatio", name: "Fixatio", image: "baa-fixatio.webp" },
  { id: "baa-frog", name: "Frog", image: "baa-frog.webp" },
  { id: "baa-grigori", name: "Grigori", image: "baa-grigori.webp" },
  { id: "baa-the-chantry", name: "The Chantry", image: "baa-the-chantry.webp" },
  { id: "baa-the-pit", name: "The Pit", image: "baa-the-pit.webp" },
  {
    id: "baa-thrift-store",
    name: "Thrift Store",
    image: "baa-thrift-store.webp",
  },
  {
    id: "baa-university-library",
    name: "University Library",
    image: "baa-university-library.webp",
  },
  { id: "baa-haze", name: "Haze", image: "baa-haze.webp" },
  {
    id: "baa-heightened-senses",
    name: "Heightened Senses",
    image: "baa-heightened-senses.webp",
  },
  { id: "baa-hua-jiang", name: "Hua Jiang", image: "baa-hua-jiang.webp" },
  {
    id: "baa-intimidation",
    name: "Intimidation",
    image: "baa-intimidation.webp",
  },
  { id: "baa-jacob-frost", name: "Jacob Frost", image: "baa-jacob-frost.webp" },
  {
    id: "baa-joseph-drake",
    name: "Joseph Drake",
    image: "baa-joseph-drake.webp",
  },
  {
    id: "baa-knowledge-is-power",
    name: "Knowledge is Power",
    image: "baa-knowledge-is-power.webp",
  },
  {
    id: "baa-lorenzo-murik",
    name: "Lorenzo Murik",
    image: "baa-lorenzo-murik.webp",
  },
  { id: "baa-mesmerize", name: "Mesmerize", image: "baa-mesmerize.webp" },
  { id: "baa-out-of-time", name: "Out of Time", image: "baa-out-of-time.webp" },
  {
    id: "baa-peer-pressure",
    name: "Peer Pressure",
    image: "baa-peer-pressure.webp",
  },
  { id: "baa-phuoc-dihn", name: "Phuoc Dihn", image: "baa-phuoc-dihn.webp" },
  { id: "baa-premonition", name: "Premonition", image: "baa-premonition.webp" },
  {
    id: "baa-rain-of-blood",
    name: "Rain of Blood",
    image: "baa-rain-of-blood.webp",
  },
  {
    id: "baa-recruitment-drive",
    name: "Recruitment Drive",
    image: "baa-recruitment-drive.webp",
  },
  {
    id: "baa-rites-of-the-blood",
    name: "Rites of the Blood",
    image: "baa-rites-of-the-blood.webp",
  },
  {
    id: "baa-scorpions-touch",
    name: "Scorpion's Touch",
    image: "baa-scorpions-touch.webp",
  },
  {
    id: "baa-seek-knowledge",
    name: "Seek Knowledge",
    image: "baa-seek-knowledge.webp",
  },
  {
    id: "baa-sleep-of-the-damned",
    name: "Sleep of the Damned",
    image: "baa-sleep-of-the-damned.webp",
  },
  {
    id: "baa-sonja-valentine",
    name: "Sonja Valentine",
    image: "baa-sonja-valentine.webp",
  },
  { id: "baa-street-brew", name: "Street Brew", image: "baa-street-brew.webp" },
  {
    id: "baa-sunrise-surprise",
    name: "Sunrise Surprise",
    image: "baa-sunrise-surprise.webp",
  },
  {
    id: "baa-theft-of-vitae",
    name: "Theft of Vitae",
    image: "baa-theft-of-vitae.webp",
  },
  {
    id: "baa-third-tradition-the-progeny",
    name: "Third Tradition: The Progeny",
    image: "baa-third-tradition-the-progeny.webp",
  },
  {
    id: "baa-truth-of-blood",
    name: "Truth of Blood",
    image: "baa-truth-of-blood.webp",
  },
  {
    id: "baa-valerie-nash",
    name: "Valerie Nash",
    image: "baa-valerie-nash.webp",
  },
  { id: "baa-wendy", name: "Wendy", image: "baa-wendy.webp" },
  { id: "core-38-special", name: ".38 Special", image: "core-38-special.webp" },
  {
    id: "core-a-biting-comment",
    name: "A Biting Comment",
    image: "core-a-biting-comment.webp",
  },
  { id: "core-addict", name: "Addict", image: "core-addict.webp" },
  {
    id: "core-all-tied up",
    name: "All Tied Up",
    image: "core-all-tied up.webp",
  },
  {
    id: "core-assert-authority",
    name: "Assert Authority",
    image: "core-assert-authority.webp",
  },
  { id: "core-athlete", name: "Athlete", image: "core-athlete.webp" },
  {
    id: "core-backhanded-compliment",
    name: "Backhanded Compliment",
    image: "core-backhanded-compliment.webp",
  },
  { id: "core-bad-penny", name: "Bad Penny", image: "core-bad-penny.webp" },
  {
    id: "core-balance-of-power",
    name: "Balance of Power",
    image: "core-balance-of-power.webp",
  },
  {
    id: "core-baseball-bat",
    name: "Baseball Bat",
    image: "core-baseball-bat.webp",
  },
  {
    id: "core-base-of-power",
    name: "Base of Power",
    image: "core-base-of-power.webp",
  },
  {
    id: "core-beauty-is-a-beast",
    name: "Beauty is a Beast",
    image: "core-beauty-is-a-beast.webp",
  },
  {
    id: "core-bella-forte",
    name: "Bella Forte",
    image: "core-bella-forte.webp",
  },
  { id: "core-beretta", name: "Beretta", image: "core-beretta.webp" },
  {
    id: "core-blood-for-blood",
    name: "Blood for Blood",
    image: "core-blood-for-blood.webp",
  },
  {
    id: "core-bong-cha-park",
    name: "Bong-Cha Park",
    image: "core-bong-cha-park.webp",
  },
  { id: "core-brother", name: "Brother", image: "core-brother.webp" },
  {
    id: "core-bruno-wagner",
    name: "Bruno Wagner",
    image: "core-bruno-wagner.webp",
  },
  {
    id: "core-bunny-benitez",
    name: "Bunny Benitez",
    image: "core-bunny-benitez.webp",
  },
  {
    id: "core-burning-down-the-house",
    name: "Burning Down the House",
    image: "core-burning-down-the-house.webp",
  },
  {
    id: "core-cable-car-accident",
    name: "Cable Car Accident",
    image: "core-cable-car-accident.webp",
  },
  {
    id: "core-castro-street-party",
    name: "Castro Street Party",
    image: "core-castro-street-party.webp",
  },
  { id: "core-chef", name: "Chef", image: "core-chef.webp" },
  {
    id: "core-chinese-new-year",
    name: "Chinese New Year",
    image: "core-chinese-new-year.webp",
  },
  {
    id: "core-city-on-the-brink",
    name: "City on the Brink",
    image: "core-city-on-the-brink.webp",
  },
  {
    id: "core-cloak-of-shadows",
    name: "Cloak of Shadows",
    image: "core-cloak-of-shadows.webp",
  },
  { id: "core-cop", name: "Cop", image: "core-cop.webp" },
  {
    id: "core-coup-de-grace",
    name: "Coup de Grâce",
    image: "core-coup-de-grace.webp",
  },
  {
    id: "core-demand-obedience",
    name: "Demand Obedience",
    image: "core-demand-obedience.webp",
  },
  {
    id: "core-destroy-the-plans",
    name: "Destroy the Plans",
    image: "core-destroy-the-plans.webp",
  },
  {
    id: "core-dignity-of-the-office",
    name: "Dignity of the Office",
    image: "core-dignity-of-the-office.webp",
  },
  {
    id: "core-distraction",
    name: "Distraction",
    image: "core-distraction.webp",
  },
  { id: "core-doc", name: "Doc", image: "core-doc.webp" },
  {
    id: "core-drain-them-slowly",
    name: "Drain Them Slowly",
    image: "core-drain-them-slowly.webp",
  },
  { id: "core-drive-by", name: "Drive-By", image: "core-drive-by.webp" },
  {
    id: "core-dumpster-dive",
    name: "Dumpster Dive",
    image: "core-dumpster-dive.webp",
  },
  {
    id: "core-emergency-bloodbag",
    name: "Emergency Bloodbag",
    image: "core-emergency-bloodbag.webp",
  },
  {
    id: "core-everything-is-connected",
    name: "Everything is Connected",
    image: "core-everything-is-connected.webp",
  },
  {
    id: "core-fame-and-fortune",
    name: "Fame & Fortune",
    image: "core-fame-and-fortune.webp",
  },
  {
    id: "core-faulty-logic",
    name: "Faulty Logic",
    image: "core-faulty-logic.webp",
  },
  {
    id: "core-first-tradition-the-masquerade",
    name: "First Tradition: The Masquerade",
    image: "core-first-tradition-the-masquerade.webp",
  },
  { id: "core-fleetness", name: "Fleetness", image: "core-fleetness.webp" },
  { id: "core-flick", name: "Flick", image: "core-flick.webp" },
  {
    id: "core-fragmented-mind",
    name: "Fragmented Mind",
    image: "core-fragmented-mind.webp",
  },
  { id: "core-free-money", name: "Free Money", image: "core-free-money.webp" },
  {
    id: "core-gallery-opening",
    name: "Gallery Opening",
    image: "core-gallery-opening.webp",
  },
  { id: "core-gang-up", name: "Gang Up", image: "core-gang-up.webp" },
  { id: "core-greed", name: "Greed", image: "core-greed.webp" },
  { id: "core-guvnah", name: "Guv'nah", image: "core-guvnah.webp" },
  {
    id: "core-artist-lofts",
    name: "Artist Lofts",
    image: "core-artist-lofts.webp",
  },
  {
    id: "core-dragons-roost",
    name: "Dragon's Roost",
    image: "core-dragons-roost.webp",
  },
  {
    id: "core-house-of-pain",
    name: "House of Pain",
    image: "core-house-of-pain.webp",
  },
  {
    id: "core-old-post-office",
    name: "Old Post Office",
    image: "core-old-post-office.webp",
  },
  {
    id: "core-royal-retreat",
    name: "Royal Retreat",
    image: "core-royal-retreat.webp",
  },
  {
    id: "core-the-dockyards",
    name: "The Dockyards",
    image: "core-the-dockyards.webp",
  },
  {
    id: "core-the-madhouse",
    name: "The Madhouse",
    image: "core-the-madhouse.webp",
  },
  {
    id: "core-the-penthouse",
    name: "The Penthouse",
    image: "core-the-penthouse.webp",
  },
  {
    id: "core-hedge-your-bets",
    name: "Hedge Your Bets",
    image: "core-hedge-your-bets.webp",
  },
  { id: "core-herald", name: "Herald", image: "core-herald.webp" },
  {
    id: "core-holdout-dagger",
    name: "Holdout Dagger",
    image: "core-holdout-dagger.webp",
  },
  {
    id: "core-humberto-garcia",
    name: "Humberto Garcia",
    image: "core-humberto-garcia.webp",
  },
  { id: "core-humiliate", name: "Humiliate", image: "core-humiliate.webp" },
  {
    id: "core-hunt-the-hunters",
    name: "Hunt the Hunters",
    image: "core-hunt-the-hunters.webp",
  },
  { id: "core-hydra", name: "Hydra", image: "core-hydra.webp" },
  {
    id: "core-incite-rebellion",
    name: "Incite Rebellion",
    image: "core-incite-rebellion.webp",
  },
  { id: "core-influencer", name: "Influencer", image: "core-influencer.webp" },
  {
    id: "core-inmate-745943",
    name: "Inmate #745943",
    image: "core-inmate-745943.webp",
  },
  {
    id: "core-insanity-defense",
    name: "Insanity Defense",
    image: "core-insanity-defense.webp",
  },
  {
    id: "core-iris-lokken",
    name: "Iris Lokken",
    image: "core-iris-lokken.webp",
  },
  {
    id: "core-irresistible-voice",
    name: "Irresistible Voice",
    image: "core-irresistible-voice.webp",
  },
  { id: "core-jesus", name: "Jesús", image: "core-jesus.webp" },
  { id: "core-johnny", name: "Johnny", image: "core-johnny.webp" },
  {
    id: "core-john-kartunen",
    name: "John Kartunen",
    image: "core-john-kartunen.webp",
  },
  {
    id: "core-june-bryant",
    name: "June Bryant",
    image: "core-june-bryant.webp",
  },
  { id: "core-karma", name: "Karma", image: "core-karma.webp" },
  {
    id: "core-keeper-of-elysium",
    name: "Keeper of Elysium",
    image: "core-keeper-of-elysium.webp",
  },
  { id: "core-kneecapped", name: "Kneecapped", image: "core-kneecapped.webp" },
  {
    id: "core-know-your-place",
    name: "Know Your Place",
    image: "core-know-your-place.webp",
  },
  {
    id: "core-late-night-snack",
    name: "Late-Night Snack",
    image: "core-late-night-snack.webp",
  },
  {
    id: "core-lightning-strike",
    name: "Lightning Strike",
    image: "core-lightning-strike.webp",
  },
  { id: "core-lixue-chen", name: "Lixue Chen", image: "core-lixue-chen.webp" },
  { id: "core-liza-holt", name: "Liza Holt", image: "core-liza-holt.webp" },
  { id: "core-lolita", name: "Lolita", image: "core-lolita.webp" },
  {
    id: "core-long-term-investment",
    name: "Long-Term Investment",
    image: "core-long-term-investment.webp",
  },
  { id: "core-lost-glory", name: "Lost Glory", image: "core-lost-glory.webp" },
  {
    id: "core-manipulate-the-masses",
    name: "Manipulate the Masses",
    image: "core-manipulate-the-masses.webp",
  },
  { id: "core-marked-man", name: "Marked Man", image: "core-marked-man.webp" },
  {
    id: "core-meeting-at-alcatraz",
    name: "Meeting at Alcatraz",
    image: "core-meeting-at-alcatraz.webp",
  },
  { id: "core-mercy", name: "Mercy", image: "core-mercy.webp" },
  {
    id: "core-molotov-cocktail",
    name: "Molotov Cocktail",
    image: "core-molotov-cocktail.webp",
  },
  {
    id: "core-montgomery-white",
    name: "Montgomery White",
    image: "core-montgomery-white.webp",
  },
  {
    id: "core-muhammad-zadeh",
    name: "Muhammad Zadeh",
    image: "core-muhammad-zadeh.webp",
  },
  { id: "core-nancy-witt", name: "Nancy Witt", image: "core-nancy-witt.webp" },
  { id: "core-playthings", name: "Playthings", image: "core-playthings.webp" },
  { id: "core-power-play", name: "Power Play", image: "core-power-play.webp" },
  { id: "core-pr-firm", name: "PR Firm", image: "core-pr-firm.webp" },
  { id: "core-primogen", name: "Primogen", image: "core-primogen.webp" },
  {
    id: "core-prince-of-the-city",
    name: "Prince of the City",
    image: "core-prince-of-the-city.webp",
  },
  {
    id: "core-protests-in-the-streets",
    name: "Protests in the Streets",
    image: "core-protests-in-the-streets.webp",
  },
  {
    id: "core-rain-on-your-parade",
    name: "Rain on Your Parade",
    image: "core-rain-on-your-parade.webp",
  },
  {
    id: "core-randolph-marz",
    name: "Randolph Marz",
    image: "core-randolph-marz.webp",
  },
  {
    id: "core-royal-review",
    name: "Royal Review",
    image: "core-royal-review.webp",
  },
  {
    id: "core-san-francisco-fog",
    name: "San Francisco Fog",
    image: "core-san-francisco-fog.webp",
  },
  {
    id: "core-scoped-30-06",
    name: "Scoped .30-06",
    image: "core-scoped-30-06.webp",
  },
  {
    id: "core-scry-the-soul",
    name: "Scry the Soul",
    image: "core-scry-the-soul.webp",
  },
  {
    id: "core-search-engine",
    name: "Search Engine",
    image: "core-search-engine.webp",
  },
  { id: "core-seduction", name: "Seduction", image: "core-seduction.webp" },
  { id: "core-seneschal", name: "Seneschal", image: "core-seneschal.webp" },
  { id: "core-shades", name: "Shades", image: "core-shades.webp" },
  { id: "core-sheriff", name: "Sheriff", image: "core-sheriff.webp" },
  {
    id: "core-skateboarder",
    name: "Skateboarder",
    image: "core-skateboarder.webp",
  },
  { id: "core-skunk", name: "Skunk", image: "core-skunk.webp" },
  {
    id: "core-slap-in-the-face",
    name: "Slap in the Face",
    image: "core-slap-in-the-face.webp",
  },
  {
    id: "core-smoke-em-out",
    name: "Smoke 'Em Out",
    image: "core-smoke-em-out.webp",
  },
  {
    id: "core-special-affairs-division",
    name: "Special Affairs Division",
    image: "core-special-affairs-division.webp",
  },
  {
    id: "core-steal-the-spotlight",
    name: "Steal the Spotlight",
    image: "core-steal-the-spotlight.webp",
  },
  {
    id: "core-stevie-osborn",
    name: "Stevie Osborn",
    image: "core-stevie-osborn.webp",
  },
  {
    id: "core-street-preacher",
    name: "Street Preacher",
    image: "core-street-preacher.webp",
  },
  {
    id: "core-strength-in-numbers",
    name: "Strength in Numbers",
    image: "core-strength-in-numbers.webp",
  },
  { id: "core-student", name: "Student", image: "core-student.webp" },
  {
    id: "core-sucker-punch",
    name: "Sucker Punch",
    image: "core-sucker-punch.webp",
  },
  { id: "core-sweetums", name: "Sweetums", image: "core-sweetums.webp" },
  { id: "core-terrorize", name: "Terrorize", image: "core-terrorize.webp" },
  {
    id: "core-the-cossack",
    name: "The Cossack",
    image: "core-the-cossack.webp",
  },
  {
    id: "core-the-end-is-nigh",
    name: "The End is Nigh",
    image: "core-the-end-is-nigh.webp",
  },
  { id: "core-the-hunger", name: "The Hunger", image: "core-the-hunger.webp" },
  {
    id: "core-the-last-word",
    name: "The Last Word",
    image: "core-the-last-word.webp",
  },
  {
    id: "core-the-mighty-fall",
    name: "The Mighty Fall",
    image: "core-the-mighty-fall.webp",
  },
  { id: "core-the-spoils", name: "The Spoils", image: "core-the-spoils.webp" },
  { id: "core-throat-rip", name: "Throat Rip", image: "core-throat-rip.webp" },
  { id: "core-tour-guide", name: "Tour Guide", image: "core-tour-guide.webp" },
  { id: "core-turf-war", name: "Turf War", image: "core-turf-war.webp" },
  { id: "core-ty-smith", name: "Ty Smith", image: "core-ty-smith.webp" },
  { id: "core-unhinged", name: "Unhinged", image: "core-unhinged.webp" },
  {
    id: "core-unswayable-mind",
    name: "Unswayable Mind",
    image: "core-unswayable-mind.webp",
  },
  { id: "core-vagrant", name: "Vagrant", image: "core-vagrant.webp" },
  { id: "core-velvet", name: "Velvet", image: "core-velvet.webp" },
  {
    id: "core-wandering-the-bart-tunnels",
    name: "Wandering the BART Tunnels",
    image: "core-wandering-the-bart-tunnels.webp",
  },
  {
    id: "core-whispering-campaign",
    name: "Whispering Campaign",
    image: "core-whispering-campaign.webp",
  },
  { id: "core-yusuf-kaya", name: "Yusuf Kaya", image: "core-yusuf-kaya.webp" },
  { id: "core-zhang-wei", name: "Zhang Wei", image: "core-zhang-wei.webp" },
  {
    id: "xxx-freddy-usher",
    name: "Freddy Usher",
    image: "xxx-freddy-usher.webp",
  },
  { id: "xxx-smoke", name: "Smoke", image: "xxx-smoke.webp" },
];
