export const cards = [
  { id: "baa-absolution", name: "Absolution", image: "baa-absolution.png" },
  {
    id: "baa-alejandro-lopez",
    name: "Alejandro Lopez",
    image: "baa-alejandro-lopez.png",
  },
  {
    id: "baa-all-the-angles",
    name: "All the Angles",
    image: "baa-all-the-angles.png",
  },
  { id: "baa-april-smith", name: "April Smith", image: "baa-april-smith.png" },
  {
    id: "baa-athanor-corporis",
    name: "Athanor Corporis",
    image: "baa-athanor-corporis.png",
  },
  { id: "baa-aurora-nix", name: "Aurora Nix", image: "baa-aurora-nix.png" },
  {
    id: "baa-baals-caress",
    name: "Baal's Caress",
    image: "baa-baals-caress.png",
  },
  {
    id: "baa-back-to-formula",
    name: "Back to Formula",
    image: "baa-back-to-formula.png",
  },
  { id: "baa-backup", name: "Backup", image: "baa-backup.png" },
  {
    id: "baa-blood-makes-noise",
    name: "Blood Makes Noise",
    image: "baa-blood-makes-noise.png",
  },
  {
    id: "baa-blood-of-potency",
    name: "Blood of Potency",
    image: "baa-blood-of-potency.png",
  },
  { id: "baa-break-down", name: "Break Down", image: "baa-break-down.png" },
  { id: "baa-calcinatio", name: "Calcinatio", image: "baa-calcinatio.png" },
  {
    id: "baa-caleb-walker",
    name: "Caleb Walker",
    image: "baa-caleb-walker.png",
  },
  { id: "baa-candi-liu", name: "Candi Liu", image: "baa-candi-liu.png" },
  {
    id: "baa-claudia-sterling",
    name: "Claudia Sterling",
    image: "baa-claudia-sterling.png",
  },
  { id: "baa-crossbow", name: "Crossbow", image: "baa-crossbow.png" },
  {
    id: "baa-dangerous-mixture",
    name: "Dangerous Mixture",
    image: "baa-dangerous-mixture.png",
  },
  {
    id: "baa-darius-wolfe",
    name: "Darius Wolfe",
    image: "baa-darius-wolfe.png",
  },
  {
    id: "baa-defense-of-the-sacred-haven",
    name: "Defense of the Sacred Haven",
    image: "baa-defense-of-the-sacred-haven.png",
  },
  { id: "baa-enervate", name: "Enervate", image: "baa-enervate.png" },
  { id: "baa-envelop", name: "Envelop", image: "baa-envelop.png" },
  {
    id: "baa-extinguish-vitae",
    name: "Extinguish Vitae",
    image: "baa-extinguish-vitae.png",
  },
  { id: "baa-faith-gray", name: "Faith Gray", image: "baa-faith-gray.png" },
  { id: "baa-far-reach", name: "Far Reach", image: "baa-far-reach.png" },
  {
    id: "baa-first-ones-free",
    name: "First One's Free",
    image: "baa-first-ones-free.png",
  },
  { id: "baa-fixatio", name: "Fixatio", image: "baa-fixatio.png" },
  { id: "baa-frog", name: "Frog", image: "baa-frog.png" },
  { id: "baa-grigori", name: "Grigori", image: "baa-grigori.png" },
  { id: "baa-the-chantry", name: "The Chantry", image: "baa-the-chantry.png" },
  { id: "baa-the-pit", name: "The Pit", image: "baa-the-pit.png" },
  {
    id: "baa-thrift-store",
    name: "Thrift Store",
    image: "baa-thrift-store.png",
  },
  {
    id: "baa-university-library",
    name: "University Library",
    image: "baa-university-library.png",
  },
  { id: "baa-haze", name: "Haze", image: "baa-haze.png" },
  {
    id: "baa-heightened-senses",
    name: "Heightened Senses",
    image: "baa-heightened-senses.png",
  },
  { id: "baa-hua-jiang", name: "Hua Jiang", image: "baa-hua-jiang.png" },
  {
    id: "baa-intimidation",
    name: "Intimidation",
    image: "baa-intimidation.png",
  },
  { id: "baa-jacob-frost", name: "Jacob Frost", image: "baa-jacob-frost.png" },
  {
    id: "baa-joseph-drake",
    name: "Joseph Drake",
    image: "baa-joseph-drake.png",
  },
  {
    id: "baa-knowledge-is-power",
    name: "Knowledge is Power",
    image: "baa-knowledge-is-power.png",
  },
  {
    id: "baa-lorenzo-murik",
    name: "Lorenzo Murik",
    image: "baa-lorenzo-murik.png",
  },
  { id: "baa-mesmerize", name: "Mesmerize", image: "baa-mesmerize.png" },
  { id: "baa-out-of-time", name: "Out of Time", image: "baa-out-of-time.png" },
  {
    id: "baa-peer-pressure",
    name: "Peer Pressure",
    image: "baa-peer-pressure.png",
  },
  { id: "baa-phuoc-dihn", name: "Phuoc Dihn", image: "baa-phuoc-dihn.png" },
  { id: "baa-premonition", name: "Premonition", image: "baa-premonition.png" },
  {
    id: "baa-rain-of-blood",
    name: "Rain of Blood",
    image: "baa-rain-of-blood.png",
  },
  {
    id: "baa-recruitment-drive",
    name: "Recruitment Drive",
    image: "baa-recruitment-drive.png",
  },
  {
    id: "baa-rites-of-the-blood",
    name: "Rites of the Blood",
    image: "baa-rites-of-the-blood.png",
  },
  {
    id: "baa-scorpions-touch",
    name: "Scorpion's Touch",
    image: "baa-scorpions-touch.png",
  },
  {
    id: "baa-seek-knowledge",
    name: "Seek Knowledge",
    image: "baa-seek-knowledge.png",
  },
  {
    id: "baa-sleep-of-the-damned",
    name: "Sleep of the Damned",
    image: "baa-sleep-of-the-damned.png",
  },
  {
    id: "baa-sonja-valentine",
    name: "Sonja Valentine",
    image: "baa-sonja-valentine.png",
  },
  { id: "baa-street-brew", name: "Street Brew", image: "baa-street-brew.png" },
  {
    id: "baa-sunrise-surprise",
    name: "Sunrise Surprise",
    image: "baa-sunrise-surprise.png",
  },
  {
    id: "baa-theft-of-vitae",
    name: "Theft of Vitae",
    image: "baa-theft-of-vitae.png",
  },
  {
    id: "baa-third-tradition-the-progeny",
    name: "Third Tradition: The Progeny",
    image: "baa-third-tradition-the-progeny.png",
  },
  {
    id: "baa-truth-of-blood",
    name: "Truth of Blood",
    image: "baa-truth-of-blood.png",
  },
  {
    id: "baa-valerie-nash",
    name: "Valerie Nash",
    image: "baa-valerie-nash.png",
  },
  { id: "baa-wendy", name: "Wendy", image: "baa-wendy.png" },
  ////////////////////
  { id: "core-38-special", name: ".38 Special", image: "core-38-special.png" },
  {
    id: "core-a-biting-comment",
    name: "A Biting Comment",
    image: "core-a-biting-comment.png",
  },
  { id: "core-addict", name: "Addict", image: "core-addict.png" },
  {
    id: "core-all-tied up",
    name: "All Tied Up",
    image: "core-all-tied up.png",
  },
  {
    id: "core-assert-authority",
    name: "Assert Authority",
    image: "core-assert-authority.png",
  },
  { id: "core-athlete", name: "Athlete", image: "core-athlete.png" },
  {
    id: "core-backhanded-compliment",
    name: "Backhanded Compliment",
    image: "core-backhanded-compliment.png",
  },
  { id: "core-bad-penny", name: "Bad Penny", image: "core-bad-penny.png" },
  {
    id: "core-balance-of-power",
    name: "Balance of Power",
    image: "core-balance-of-power.png",
  },
  {
    id: "core-baseball-bat",
    name: "Baseball Bat",
    image: "core-baseball-bat.png",
  },
  {
    id: "core-base-of-power",
    name: "Base of Power",
    image: "core-base-of-power.png",
  },
  {
    id: "core-beauty-is-a-beast",
    name: "Beauty is a Beast",
    image: "core-beauty-is-a-beast.png",
  },
  {
    id: "core-bella-forte",
    name: "Bella Forte",
    image: "core-bella-forte.png",
  },
  { id: "core-beretta", name: "Beretta", image: "core-beretta.png" },
  {
    id: "core-blood-for-blood",
    name: "Blood for Blood",
    image: "core-blood-for-blood.png",
  },
  {
    id: "core-bong-cha-park",
    name: "Bong-Cha Park",
    image: "core-bong-cha-park.png",
  },
  { id: "core-brother", name: "Brother", image: "core-brother.png" },
  {
    id: "core-bruno-wagner",
    name: "Bruno Wagner",
    image: "core-bruno-wagner.png",
  },
  {
    id: "core-bunny-benitez",
    name: "Bunny Benitez",
    image: "core-bunny-benitez.png",
  },
  {
    id: "core-burning-down-the-house",
    name: "Burning Down the House",
    image: "core-burning-down-the-house.png",
  },
  {
    id: "core-cable-car-accident",
    name: "Cable Car Accident",
    image: "core-cable-car-accident.png",
  },
  {
    id: "core-castro-street-party",
    name: "Castro Street Party",
    image: "core-castro-street-party.png",
  },
  { id: "core-chef", name: "Chef", image: "core-chef.png" },
  {
    id: "core-chinese-new-year",
    name: "Chinese New Year",
    image: "core-chinese-new-year.png",
  },
  {
    id: "core-city-on-the-brink",
    name: "City on the Brink",
    image: "core-city-on-the-brink.png",
  },
  {
    id: "core-cloak-of-shadows",
    name: "Cloak of Shadows",
    image: "core-cloak-of-shadows.png",
  },
  { id: "core-cop", name: "Cop", image: "core-cop.png" },
  {
    id: "core-coup-de-grace",
    name: "Coup de Grâce",
    image: "core-coup-de-grace.png",
  },
  {
    id: "core-demand-obedience",
    name: "Demand Obedience",
    image: "core-demand-obedience.png",
  },
  {
    id: "core-destroy-the-plans",
    name: "Destroy the Plans",
    image: "core-destroy-the-plans.png",
  },
  {
    id: "core-dignity-of-the-office",
    name: "Dignity of the Office",
    image: "core-dignity-of-the-office.png",
  },
  {
    id: "core-distraction",
    name: "Distraction",
    image: "core-distraction.png",
  },
  { id: "core-doc", name: "Doc", image: "core-doc.png" },
  {
    id: "core-drain-them-slowly",
    name: "Drain Them Slowly",
    image: "core-drain-them-slowly.png",
  },
  { id: "core-drive-by", name: "Drive-By", image: "core-drive-by.png" },
  {
    id: "core-dumpster-dive",
    name: "Dumpster Dive",
    image: "core-dumpster-dive.png",
  },
  {
    id: "core-emergency-bloodbag",
    name: "Emergency Bloodbag",
    image: "core-emergency-bloodbag.png",
  },
  {
    id: "core-everything-is-connected",
    name: "Everything is Connected",
    image: "core-everything-is-connected.png",
  },
  {
    id: "core-fame-and-fortune",
    name: "Fame & Fortune",
    image: "core-fame-and-fortune.png",
  },
  {
    id: "core-faulty-logic",
    name: "Faulty Logic",
    image: "core-faulty-logic.png",
  },
  {
    id: "core-first-tradition-the-masquerade",
    name: "First Tradition: The Masquerade",
    image: "core-first-tradition-the-masquerade.png",
  },
  { id: "core-fleetness", name: "Fleetness", image: "core-fleetness.png" },
  { id: "core-flick", name: "Flick", image: "core-flick.png" },
  {
    id: "core-fragmented-mind",
    name: "Fragmented Mind",
    image: "core-fragmented-mind.png",
  },
  { id: "core-free-money", name: "Free Money", image: "core-free-money.png" },
  {
    id: "core-gallery-opening",
    name: "Gallery Opening",
    image: "core-gallery-opening.png",
  },
  { id: "core-gang-up", name: "Gang Up", image: "core-gang-up.png" },
  { id: "core-greed", name: "Greed", image: "core-greed.png" },
  { id: "core-guvnah", name: "Guv'nah", image: "core-guvnah.png" },
  {
    id: "core-artist-lofts",
    name: "Artist Lofts",
    image: "core-artist-lofts.png",
  },
  {
    id: "core-dragons-roost",
    name: "Dragon's Roost",
    image: "core-dragons-roost.png",
  },
  {
    id: "core-house-of-pain",
    name: "House of Pain",
    image: "core-house-of-pain.png",
  },
  {
    id: "core-old-post-office",
    name: "Old Post Office",
    image: "core-old-post-office.png",
  },
  {
    id: "core-royal-retreat",
    name: "Royal Retreat",
    image: "core-royal-retreat.png",
  },
  {
    id: "core-the-dockyards",
    name: "The Dockyards",
    image: "core-the-dockyards.png",
  },
  {
    id: "core-the-madhouse",
    name: "The Madhouse",
    image: "core-the-madhouse.png",
  },
  {
    id: "core-the-penthouse",
    name: "The Penthouse",
    image: "core-the-penthouse.png",
  },
  {
    id: "core-hedge-your-bets",
    name: "Hedge Your Bets",
    image: "core-hedge-your-bets.png",
  },
  { id: "core-herald", name: "Herald", image: "core-herald.png" },
  {
    id: "core-holdout-dagger",
    name: "Holdout Dagger",
    image: "core-holdout-dagger.png",
  },
  {
    id: "core-humberto-garcia",
    name: "Humberto Garcia",
    image: "core-humberto-garcia.png",
  },
  { id: "core-humiliate", name: "Humiliate", image: "core-humiliate.png" },
  {
    id: "core-hunt-the-hunters",
    name: "Hunt the Hunters",
    image: "core-hunt-the-hunters.png",
  },
  { id: "core-hydra", name: "Hydra", image: "core-hydra.png" },
  {
    id: "core-incite-rebellion",
    name: "Incite Rebellion",
    image: "core-incite-rebellion.png",
  },
  { id: "core-influencer", name: "Influencer", image: "core-influencer.png" },
  {
    id: "core-inmate-745943",
    name: "Inmate #745943",
    image: "core-inmate-745943.png",
  },
  {
    id: "core-insanity-defense",
    name: "Insanity Defense",
    image: "core-insanity-defense.png",
  },
  {
    id: "core-iris-lokken",
    name: "Iris Lokken",
    image: "core-iris-lokken.png",
  },
  {
    id: "core-irresistible-voice",
    name: "Irresistible Voice",
    image: "core-irresistible-voice.png",
  },
  { id: "core-jesus", name: "Jesús", image: "core-jesus.png" },
  { id: "core-johnny", name: "Johnny", image: "core-johnny.png" },
  {
    id: "core-john-kartunen",
    name: "John Kartunen",
    image: "core-john-kartunen.png",
  },
  {
    id: "core-june-bryant",
    name: "June Bryant",
    image: "core-june-bryant.png",
  },
  { id: "core-karma", name: "Karma", image: "core-karma.png" },
  {
    id: "core-keeper-of-elysium",
    name: "Keeper of Elysium",
    image: "core-keeper-of-elysium.png",
  },
  { id: "core-kneecapped", name: "Kneecapped", image: "core-kneecapped.png" },
  {
    id: "core-know-your-place",
    name: "Know Your Place",
    image: "core-know-your-place.png",
  },
  {
    id: "core-late-night-snack",
    name: "Late-Night Snack",
    image: "core-late-night-snack.png",
  },
  {
    id: "core-lightning-strike",
    name: "Lightning Strike",
    image: "core-lightning-strike.png",
  },
  { id: "core-lixue-chen", name: "Lixue Chen", image: "core-lixue-chen.png" },
  { id: "core-liza-holt", name: "Liza Holt", image: "core-liza-holt.png" },
  { id: "core-lolita", name: "Lolita", image: "core-lolita.png" },
  {
    id: "core-long-term-investment",
    name: "Long-Term Investment",
    image: "core-long-term-investment.png",
  },
  { id: "core-lost-glory", name: "Lost Glory", image: "core-lost-glory.png" },
  {
    id: "core-manipulate-the-masses",
    name: "Manipulate the Masses",
    image: "core-manipulate-the-masses.png",
  },
  { id: "core-marked-man", name: "Marked Man", image: "core-marked-man.png" },
  {
    id: "core-meeting-at-alcatraz",
    name: "Meeting at Alcatraz",
    image: "core-meeting-at-alcatraz.png",
  },
  { id: "core-mercy", name: "Mercy", image: "core-mercy.png" },
  {
    id: "core-molotov-cocktail",
    name: "Molotov Cocktail",
    image: "core-molotov-cocktail.png",
  },
  {
    id: "core-montgomery-white",
    name: "Montgomery White",
    image: "core-montgomery-white.png",
  },
  {
    id: "core-muhammad-zadeh",
    name: "Muhammad Zadeh",
    image: "core-muhammad-zadeh.png",
  },
  { id: "core-nancy-witt", name: "Nancy Witt", image: "core-nancy-witt.png" },
  { id: "core-playthings", name: "Playthings", image: "core-playthings.png" },
  { id: "core-power-play", name: "Power Play", image: "core-power-play.png" },
  { id: "core-pr-firm", name: "PR Firm", image: "core-pr-firm.png" },
  { id: "core-primogen", name: "Primogen", image: "core-primogen.png" },
  {
    id: "core-prince-of-the-city",
    name: "Prince of the City",
    image: "core-prince-of-the-city.png",
  },
  {
    id: "core-protests-in-the-streets",
    name: "Protests in the Streets",
    image: "core-protests-in-the-streets.png",
  },
  {
    id: "core-rain-on-your-parade",
    name: "Rain on Your Parade",
    image: "core-rain-on-your-parade.png",
  },
  {
    id: "core-randolph-marz",
    name: "Randolph Marz",
    image: "core-randolph-marz.png",
  },
  {
    id: "core-royal-review",
    name: "Royal Review",
    image: "core-royal-review.png",
  },
  {
    id: "core-san-francisco-fog",
    name: "San Francisco Fog",
    image: "core-san-francisco-fog.png",
  },
  {
    id: "core-scoped-30-06",
    name: "Scoped .30-06",
    image: "core-scoped-30-06.png",
  },
  {
    id: "core-scry-the-soul",
    name: "Scry the Soul",
    image: "core-scry-the-soul.png",
  },
  {
    id: "core-search-engine",
    name: "Search Engine",
    image: "core-search-engine.png",
  },
  { id: "core-seduction", name: "Seduction", image: "core-seduction.png" },
  { id: "core-seneschal", name: "Seneschal", image: "core-seneschal.png" },
  { id: "core-shades", name: "Shades", image: "core-shades.png" },
  { id: "core-sheriff", name: "Sheriff", image: "core-sheriff.png" },
  {
    id: "core-skateboarder",
    name: "Skateboarder",
    image: "core-skateboarder.png",
  },
  { id: "core-skunk", name: "Skunk", image: "core-skunk.png" },
  {
    id: "core-slap-in-the-face",
    name: "Slap in the Face",
    image: "core-slap-in-the-face.png",
  },
  {
    id: "core-smoke-em-out",
    name: "Smoke 'Em Out",
    image: "core-smoke-em-out.png",
  },
  {
    id: "core-special-affairs-division",
    name: "Special Affairs Division",
    image: "core-special-affairs-division.png",
  },
  {
    id: "core-steal-the-spotlight",
    name: "Steal the Spotlight",
    image: "core-steal-the-spotlight.png",
  },
  {
    id: "core-stevie-osborn",
    name: "Stevie Osborn",
    image: "core-stevie-osborn.png",
  },
  {
    id: "core-street-preacher",
    name: "Street Preacher",
    image: "core-street-preacher.png",
  },
  {
    id: "core-strength-in-numbers",
    name: "Strength in Numbers",
    image: "core-strength-in-numbers.png",
  },
  { id: "core-student", name: "Student", image: "core-student.png" },
  {
    id: "core-sucker-punch",
    name: "Sucker Punch",
    image: "core-sucker-punch.png",
  },
  { id: "core-sweetums", name: "Sweetums", image: "core-sweetums.png" },
  { id: "core-terrorize", name: "Terrorize", image: "core-terrorize.png" },
  {
    id: "core-the-cossack",
    name: "The Cossack",
    image: "core-the-cossack.png",
  },
  {
    id: "core-the-end-is-nigh",
    name: "The End is Nigh",
    image: "core-the-end-is-nigh.png",
  },
  { id: "core-the-hunger", name: "The Hunger", image: "core-the-hunger.png" },
  {
    id: "core-the-last-word",
    name: "The Last Word",
    image: "core-the-last-word.png",
  },
  {
    id: "core-the-mighty-fall",
    name: "The Mighty Fall",
    image: "core-the-mighty-fall.png",
  },
  { id: "core-the-spoils", name: "The Spoils", image: "core-the-spoils.png" },
  { id: "core-throat-rip", name: "Throat Rip", image: "core-throat-rip.png" },
  { id: "core-tour-guide", name: "Tour Guide", image: "core-tour-guide.png" },
  { id: "core-turf-war", name: "Turf War", image: "core-turf-war.png" },
  { id: "core-ty-smith", name: "Ty Smith", image: "core-ty-smith.png" },
  { id: "core-unhinged", name: "Unhinged", image: "core-unhinged.png" },
  {
    id: "core-unswayable-mind",
    name: "Unswayable Mind",
    image: "core-unswayable-mind.png",
  },
  { id: "core-vagrant", name: "Vagrant", image: "core-vagrant.png" },
  { id: "core-velvet", name: "Velvet", image: "core-velvet.png" },
  {
    id: "core-wandering-the-bart-tunnels",
    name: "Wandering the BART Tunnels",
    image: "core-wandering-the-bart-tunnels.png",
  },
  {
    id: "core-whispering-campaign",
    name: "Whispering Campaign",
    image: "core-whispering-campaign.png",
  },
  { id: "core-yusuf-kaya", name: "Yusuf Kaya", image: "core-yusuf-kaya.png" },
  { id: "core-zhang-wei", name: "Zhang Wei", image: "core-zhang-wei.png" },
  ////////////
  {
    id: "xxx-freddy-usher",
    name: "Freddy Usher",
    image: "xxx-freddy-usher.png",
  },
  { id: "xxx-smoke", name: "Smoke", image: "xxx-smoke.png" },
];
