export const cards = [
  { id: "baa-absolution", name: "Absolution", image: "baa-absolution.png" },
  {
    id: "baa-alejandro-lopez",
    name: "Alejandro Lopez",
    image: "baa-alejandro-lopez.png",
  },
  {
    id: "baa-all-the-angles",
    name: "All the Angles",
    image: "baa-all-the-angles.png",
  },
  { id: "baa-april-smith", name: "April Smith", image: "baa-april-smith.png" },
  {
    id: "baa-athanor-corporis",
    name: "Athanor Corporis",
    image: "baa-athanor-corporis.png",
  },
  { id: "baa-aurora-nix", name: "Aurora Nix", image: "baa-aurora-nix.png" },
  {
    id: "baa-baals-caress",
    name: "Baal's Caress",
    image: "baa-baals-caress.png",
  },
  {
    id: "baa-back-to-formula",
    name: "Back to Formula",
    image: "baa-back-to-formula.png",
  },
  { id: "baa-backup", name: "Backup", image: "baa-backup.png" },
  {
    id: "baa-blood-makes-noise",
    name: "Blood Makes Noise",
    image: "baa-blood-makes-noise.png",
  },
  {
    id: "baa-blood-of-potency",
    name: "Blood of Potency",
    image: "baa-blood-of-potency.png",
  },
  { id: "baa-break-down", name: "Break Down", image: "baa-break-down.png" },
  { id: "baa-calcinatio", name: "Calcinatio", image: "baa-calcinatio.png" },
  {
    id: "baa-caleb-walker",
    name: "Caleb Walker",
    image: "baa-caleb-walker.png",
  },
  { id: "baa-candi-liu", name: "Candi Liu", image: "baa-candi-liu.png" },
  {
    id: "baa-claudia-sterling",
    name: "Claudia Sterling",
    image: "baa-claudia-sterling.png",
  },
  { id: "baa-crossbow", name: "Crossbow", image: "baa-crossbow.png" },
  {
    id: "baa-dangerous-mixture",
    name: "Dangerous Mixture",
    image: "baa-dangerous-mixture.png",
  },
  {
    id: "baa-darius-wolfe",
    name: "Darius Wolfe",
    image: "baa-darius-wolfe.png",
  },
  {
    id: "baa-defense-of-the-sacred-haven",
    name: "Defense of the Sacred Haven",
    image: "baa-defense-of-the-sacred-haven.png",
  },
  { id: "baa-enervate", name: "Enervate", image: "baa-enervate.png" },
  { id: "baa-envelop", name: "Envelop", image: "baa-envelop.png" },
  {
    id: "baa-extinguish-vitae",
    name: "Extinguish Vitae",
    image: "baa-extinguish-vitae.png",
  },
  { id: "baa-faith-gray", name: "Faith Gray", image: "baa-faith-gray.png" },
  { id: "baa-far-reach", name: "Far Reach", image: "baa-far-reach.png" },
  {
    id: "baa-first-ones-free",
    name: "First One's Free",
    image: "baa-first-ones-free.png",
  },
  { id: "baa-fixatio", name: "Fixatio", image: "baa-fixatio.png" },
  { id: "baa-frog", name: "Frog", image: "baa-frog.png" },
  { id: "baa-grigori", name: "Grigori", image: "baa-grigori.png" },
  { id: "baa-the-chantry", name: "The Chantry", image: "baa-the-chantry.png" },
  { id: "baa-the-pit", name: "The Pit", image: "baa-the-pit.png" },
  {
    id: "baa-thrift-store",
    name: "Thrift Store",
    image: "baa-thrift-store.png",
  },
  {
    id: "baa-university-library",
    name: "University Library",
    image: "baa-university-library.png",
  },
  { id: "baa-haze", name: "Haze", image: "baa-haze.png" },
  {
    id: "baa-heightened-senses",
    name: "Heightened Senses",
    image: "baa-heightened-senses.png",
  },
  { id: "baa-hua-jiang", name: "Hua Jiang", image: "baa-hua-jiang.png" },
  {
    id: "baa-intimidation",
    name: "Intimidation",
    image: "baa-intimidation.png",
  },
  { id: "baa-jacob-frost", name: "Jacob Frost", image: "baa-jacob-frost.png" },
  {
    id: "baa-joseph-drake",
    name: "Joseph Drake",
    image: "baa-joseph-drake.png",
  },
  {
    id: "baa-knowledge-is-power",
    name: "Knowledge is Power",
    image: "baa-knowledge-is-power.png",
  },
  {
    id: "baa-lorenzo-murik",
    name: "Lorenzo Murik",
    image: "baa-lorenzo-murik.png",
  },
  { id: "baa-mesmerize", name: "Mesmerize", image: "baa-mesmerize.png" },
  { id: "baa-out-of-time", name: "Out of Time", image: "baa-out-of-time.png" },
  {
    id: "baa-peer-pressure",
    name: "Peer Pressure",
    image: "baa-peer-pressure.png",
  },
  { id: "baa-phuoc-dihn", name: "Phuoc Dihn", image: "baa-phuoc-dihn.png" },
  { id: "baa-premonition", name: "Premonition", image: "baa-premonition.png" },
  {
    id: "baa-rain-of-blood",
    name: "Rain of Blood",
    image: "baa-rain-of-blood.png",
  },
  {
    id: "baa-recruitment-drive",
    name: "Recruitment Drive",
    image: "baa-recruitment-drive.png",
  },
  {
    id: "baa-rites-of-the-blood",
    name: "Rites of the Blood",
    image: "baa-rites-of-the-blood.png",
  },
  {
    id: "baa-scorpions-touch",
    name: "Scorpion's Touch",
    image: "baa-scorpions-touch.png",
  },
  {
    id: "baa-seek-knowledge",
    name: "Seek Knowledge",
    image: "baa-seek-knowledge.png",
  },
  {
    id: "baa-sleep-of-the-damned",
    name: "Sleep of the Damned",
    image: "baa-sleep-of-the-damned.png",
  },
  {
    id: "baa-sonja-valentine",
    name: "Sonja Valentine",
    image: "baa-sonja-valentine.png",
  },
  { id: "baa-street-brew", name: "Street Brew", image: "baa-street-brew.png" },
  {
    id: "baa-sunrise-surprise",
    name: "Sunrise Surprise",
    image: "baa-sunrise-surprise.png",
  },
  {
    id: "baa-theft-of-vitae",
    name: "Theft of Vitae",
    image: "baa-theft-of-vitae.png",
  },
  {
    id: "baa-third-tradition-the-progeny",
    name: "Third Tradition: The Progeny",
    image: "baa-third-tradition-the-progeny.png",
  },
  {
    id: "baa-truth-of-blood",
    name: "Truth of Blood",
    image: "baa-truth-of-blood.png",
  },
  {
    id: "baa-valerie-nash",
    name: "Valerie Nash",
    image: "baa-valerie-nash.png",
  },
  { id: "baa-wendy", name: "Wendy", image: "baa-wendy.png" },
];
